### ISSUE TITLE
bug starting a new conversation

### ISSUE THREAD

**Issue by egalvis39** [iKonoTelecomunicaciones/gupshup#26]
```bash
ikonochat-dev-gupshup-1  | [2023-08-08 19:18:22,129] [ERROR@aiohttp.server] Error handling request
ikonochat-dev-gupshup-1  | Traceback (most recent call last):
ikonochat-dev-gupshup-1  |   File "/usr/lib/python3.9/site-packages/mautrix/appservice/api/intent.py", line 592, in ensure_joined
ikonochat-dev-gupshup-1  |     await self.join_room(room_id, max_retries=0)
ikonochat-dev-gupshup-1  |   File "/usr/lib/python3.9/site-packages/mautrix/appservice/api/intent.py", line 128, in wrapper
ikonochat-dev-gupshup-1  |     return await __method(*args, **kwargs)
ikonochat-dev-gupshup-1  |   File "/usr/lib/python3.9/site-packages/mautrix/client/store_updater.py", line 62, in join_room
ikonochat-dev-gupshup-1  |     room_id = await super().join_room(
ikonochat-dev-gupshup-1  |   File "/usr/lib/python3.9/site-packages/mautrix/client/api/rooms.py", line 335, in join_room
ikonochat-dev-gupshup-1  |     content = await self.api.request(
ikonochat-dev-gupshup-1  |   File "/usr/lib/python3.9/site-packages/mautrix/api.py", line 395, in request
ikonochat-dev-gupshup-1  |     resp_data, resp = await self._send(
ikonochat-dev-gupshup-1  |   File "/usr/lib/python3.9/site-packages/mautrix/api.py", line 250, in _send
ikonochat-dev-gupshup-1  |     raise make_request_error(
ikonochat-dev-gupshup-1  | mautrix.errors.request.MForbidden: You are not invited to this room.
ikonochat-dev-gupshup-1  | 
ikonochat-dev-gupshup-1  | 
ikonochat-dev-gupshup-1  | The above exception was the direct cause of the following exception:
ikonochat-dev-gupshup-1  | 
ikonochat-dev-gupshup-1  | 
ikonochat-dev-gupshup-1  | Traceback (most recent call last):
ikonochat-dev-gupshup-1  |   File "/usr/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 422, in _handle_request
ikonochat-dev-gupshup-1  |     resp = await self._request_handler(request)
ikonochat-dev-gupshup-1  |   File "/usr/lib/python3.9/site-packages/aiohttp/web_app.py", line 499, in _handle
ikonochat-dev-gupshup-1  |     resp = await handler(request)
ikonochat-dev-gupshup-1  |   File "/opt/gupshup-matrix/gupshup_matrix/web/provisioning_api.py", line 229, in template
ikonochat-dev-gupshup-1  |     msg_event_id = await portal.az.intent.send_message(portal.mxid, msg)
ikonochat-dev-gupshup-1  |   File "/usr/lib/python3.9/site-packages/mautrix/appservice/api/intent.py", line 141, in wrapper
ikonochat-dev-gupshup-1  |     await __self.ensure_joined(room_id)
ikonochat-dev-gupshup-1  |   File "/usr/lib/python3.9/site-packages/mautrix/appservice/api/intent.py", line 596, in ensure_joined
ikonochat-dev-gupshup-1  |     raise IntentError(f"Failed to join room {room_id} as {self.mxid}") from e
ikonochat-dev-gupshup-1  | mautrix.errors.base.IntentError: Failed to join room !NngSUiBZvnRiXjzffC:darknet as @gupshupbot:darknet
```

**Comment by egalvis39** [comment]
Error fixed, gupshup bot is not in the room to send the first message of the conversation
